title: The AI Moral Code
description: A Publishing Platform for Ethical AI Evaluation
url: "https://aimoralcode.org"
baseurl: ""  # leave empty if deployed at root of domain
timezone: America/Los_Angeles
future: true

collections:
  posts:
    output: true
    permalink: /posts/:year-:month-:day-:title/
  pages:
    output: true
    permalink: /:path/

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      author: "Randy J. Hinrichs"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Randy J. Hinrichs"

markdown: kramdown
theme: jekyll-theme-cayman

plugins:
  - jekyll-paginate
