title: AI Moral Code
description: A canonical taxonomy of AI values and ethical frameworks
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://aimoralcode.org" # the base hostname & protocol for your site

markdown: kramdown
permalink: pretty

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
