title: "AI Moral Code"
baseurl: ""
url: "https://aimoralcode.org"

include:
  - admin

collections:
  posts:
    output: true
    permalink: /posts/:name/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Randy J. Hinrichs"

markdown: kramdown
theme: minima

plugins:
  - jekyll-admin
