title: "The AI Moral Code"
baseurl: ""
url: "https://aimoralcode.org"
timezone: America/Los_Angeles  # or your preferred timezone
future: true
collections:
  posts:
    output: true
    permalink: /posts/:year-:month-:day-:title/
  pages:
    output: true
    permalink: /:path/

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      author: "Randy J. Hinrichs"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Randy J. Hinrichs"

markdown: kramdown
theme: minima

plugins:
  - jekyll-paginate
