title: "AI Moral Code"
baseurl: ""
url: "https://aimoralcode.org"

collections:
  posts:
    output: true
    permalink: /posts/:name/

defaults:
  - scope:
      path: "posts"
      type: "posts"
    values:
      layout: "post"
      author: "Randy J. Hinrichs"

markdown: kramdown
theme: minima
