title: The AI Moral Code
description: A Publishing Platform for Ethical AI Evaluation
url: "https://aimoralcode.org"
baseurl: ""  # Deployed at root
timezone: America/Los_Angeles
future: true

collections:
  posts:
    output: true
  pages:
    output: true

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      author: "Randy J. Hinrichs"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Randy J. Hinrichs"

markdown: kramdown
permalink: /:categories/:year/:month/:day/:title.html

plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - vendor
  - .bundle
  - Gemfile
  - Gemfile.lock
  - node_modules
  - README.md
  - LICENSE
  - .gitignore
  - netlify.toml
  - "*.sh"
