title: "AI Moral Code"
baseurl: ""  # if publishing under https://username.github.io, leave blank
url: "https://rjhinrichs.github.io"

collections:
  posts:
    output: true
    permalink: /posts/:name/

defaults:
  - scope:
      path: "posts"
      type: "posts"
    values:
      layout: "post"
      author: "Ran Hinrichs"

markdown: kramdown
theme: minima
