title: "The AI Moral Code"
baseurl: ""
url: "https://aimoralcode.org"

include:
  - admin

collections:
  - name: "posts"
    label: !!str "Blog Posts"
    folder: "_posts"
    output: true
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    permalink: /posts/{{year}}-{{month}}-{{day}}-{{slug}}/
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Date"
        name: "date"
        widget: "datetime"
      - label: "Body"
        name: "body"
        widget: "markdown"

  - name: "pages"
    label: !!str "Site Pages"
    files:
      - label: "Homepage"
        name: "index"
        file: "index.md"
        fields:
          - label: "Title"
            name: "title"
            widget: "string"
          - label: "Body"
            name: "body"
            widget: "markdown"

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Randy J. Hinrichs"

markdown: kramdown
theme: minima

plugins:
  - jekyll-admin
