name: Bug Report
description: Report a technical issue affecting the AI Moral Code repository, site, or contributor tools.
title: "[Bug] Brief title describing the issue"
labels: ["bug", "triage-needed"]
assignees:
  - rjhinrichs
body:
  - type: markdown
    attributes:
      value: |
        Use this form to report reproducible issues affecting functionality, access, formatting, or GitHub workflows. Include clear reproduction steps and system context.

  - type: input
    id: system
    attributes:
      label: System Context
      description: Describe the operating system, browser, or environment where the issue occurred.
      placeholder: e.g., Windows 11, Chrome 123, GitHub Desktop
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Provide step-by-step actions to replicate the issue.
      placeholder: |
        1. Go to the repository homepage
        2. Click on "Issues"
        3. Observe missing milestone button
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen instead?
      placeholder: e.g., Milestone creation button should be visible to repository owner
    validations:
      required: false

  - type: textarea
    id: notes
    attributes:
      label: Additional Notes or Screenshots
      description: Share any logs, screenshots, or error messages that help clarify the issue.
      placeholder: You may drag and drop files here.
    validations:
      required: false
