blank_issues_enabled: false

contact_links:
  - name: General Inquiry
    url: https://aimoralcode.org/contact
    about: For questions unrelated to a GitHub issue or contribution.

issue_templates:
  - name: Blog Contributor Request
    description: Apply to write for the AI Moral Code Blog.
    file: blog-contributor-request.yml
  - name: Feature Request
    description: Propose a new enhancement or capability.
    file: feature-request.yml
  - name: Bug Report
    description: Report a technical issue with the site or repository.
    file: bug-report.yml
  - name: General Inquiry
    description: Submit documentation notes, conceptual ideas, or questions.
    file: general-inquiry.yml
