name: Feature Request
description: Propose a new capability or enhancement.
title: "[Feature] Title"
labels: ["enhancement"]
assignees:
  - rjhinrichs
body:
  - type: markdown
    attributes:
      value: "Describe what you would like to see added or improved."

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      placeholder: What problem does this solve?
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed Solution
      placeholder: Describe how this could work.
    validations:
      required: true
