backend:
  name: github
  repo: rjhinrichs/aimoralcode
  branch: main
  auth_scope: repo
  client_id: Ov23liOpWmF7JstCGuH5

site_url: https://aimoralcode.org
media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
