name: Email New Blog Contributor Request

on:
  issues:
    types: [opened]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send email notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "New Blog Contributor Request"
          to: rhinrich@norwich.edu
          from: "AI Moral Code <${{ secrets.EMAIL_USERNAME }}>"
          content_type: text/html
          body: |
            <h2>New Blog Contributor Application</h2>
            <p><strong>Submitted Title:</strong> ${{ github.event.issue.title }}</p>
            <p><strong>Issue URL:</strong> <a href="${{ github.event.issue.html_url }}">${{ github.event.issue.html_url }}</a></p>
            <hr />
            <pre>${{ github.event.issue.body }}</pre>

